# Generated by Django 5.1.6 on 2025-03-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="friend_list", to="usuarios.userprofile"
            ),
        ),
    ]
