# Generated by Django 5.1.6 on 2025-03-30 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0006_friendship_friendrequest"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendrequest",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="friendrequest",
            name="from_user",
        ),
        migrations.RemoveField(
            model_name="friendrequest",
            name="to_user",
        ),
        migrations.RemoveField(
            model_name="friendship",
            name="friend",
        ),
        migrations.RemoveField(
            model_name="friendship",
            name="user",
        ),
        migrations.RemoveField(
            model_name="message",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="followers",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="friends",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Amistad",
        ),
        migrations.DeleteModel(
            name="FriendRequest",
        ),
        migrations.DeleteModel(
            name="Friendship",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
