# Generated by Django 5.1.6 on 2025-04-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_friendrequest_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
