# Generated by Django 5.1.6 on 2025-04-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0008_usuario_otp_usuario_otp_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
