# Generated by Django 5.2.4 on 2025-08-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='privacidad',
            field=models.CharField(choices=[('publico', 'Público'), ('amigos', 'Solo amigos'), ('privado', 'Solo yo')], default='publico', max_length=10),
        ),
    ]
